main: com.github.manu585.manusgroups.ManusGroups
name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
author: ${organization.name}
database: true
website: ${organization.url}
api-version: 1.21

commands:
  groups:
    description: Group base command
    permission: groups.use
    permission-message: You do not have permission to execute this command!
    usage: /groups

libraries:
  - com.zaxxer:HikariCP:7.0.2
  - org.mariadb.jdbc:mariadb-java-client:3.5.6